### ISSUE TITLE
Python error code

### ISSUE THREAD

**Issue by KaiBueK** [coddingtonbear/bear-to-paper#2]
Hi,

i like to import files to paper. 
But I'm receive following error messages:

 File "/usr/local/bin/bear-to-paper", line 6, in <module>
    from bear_to_paper.cmdline import main
  File "/usr/local/lib/python2.7/site-packages/bear_to_paper/cmdline.py", line 10
    def main(args: List[Text] = None):

**Comment by coddingtonbear** [comment]
Bear-to-paper requires Python 3; I think running it in a Pin Python 3 environment should sort things out for you; good luck!
